# Generated by Django 5.1.4 on 2024-12-26 01:16

from django.db import migrations, models


def create_default_store(apps, schema_editor):
    Store = apps.get_model('store', 'Store')
    if not Store.objects.filter(code='en').exists():
        Store.objects.create(code='en', name='English', is_default=True)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.RunPython(create_default_store),
    ]
