# Generated by Django 5.1.4 on 2024-12-26 00:22

import django.db.models.deletion
import modules.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'additive',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'package',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='AdditiveInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('additive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='product.additive')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additive_info', to='store.store')),
            ],
            options={
                'db_table': 'additive_info',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='CategoryChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='product.category')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='channel.channel')),
            ],
            options={
                'db_table': 'category_channel',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='PackageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='product.package')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_info', to='store.store')),
            ],
            options={
                'db_table': 'package_info',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
            ],
            options={
                'db_table': 'product',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='ProductAdditive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.additive')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additives', to='product.product')),
            ],
            options={
                'db_table': 'product_additive',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='ProductExcludeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.channel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_exclude_channel',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('info', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='product.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='store.store')),
            ],
            options={
                'db_table': 'product_info',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='ProductMediaGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='product.product')),
            ],
            options={
                'db_table': 'product_media_gallery',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
            ],
            options={
                'db_table': 'product_variant',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='ProductVariantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='product.productvariant')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_info', to='store.store')),
            ],
            options={
                'db_table': 'product_variant_info',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
    ]
