# Generated by Django 5.1.4 on 2024-12-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CategoryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='product.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_info', to='store.store')),
            ],
            options={
                'db_table': 'category_info',
            },
        ),
    ]
