# Generated by Django 5.1.4 on 2024-12-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_category_name'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='additiveinfo',
            unique_together={('additive', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='categoryinfo',
            unique_together={('category', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='packageinfo',
            unique_together={('package', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='productinfo',
            unique_together={('product', 'store')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariantinfo',
            unique_together={('product_variant', 'store')},
        ),
    ]
