# Generated by Django 5.1.4 on 2024-12-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_additiveinfo_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='name',
        ),
    ]
