# Generated by Django 5.1.4 on 2024-12-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_additive_price_alter_package_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmediagallery',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
