# Generated by Django 5.1.4 on 2025-01-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_channel_currency'),
        ('product', '0007_productmediagallery_priority'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productexcludechannel',
            unique_together={('channel', 'product')},
        ),
    ]
