# Generated by Django 5.1.4 on 2025-02-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productexcludechannel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='additive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_additive_images/'),
        ),
    ]
