# Generated by Django 5.1.4 on 2025-01-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='currency',
            field=models.CharField(default='zl', max_length=255),
            preserve_default=False,
        ),
    ]
