# Generated by Django 5.1.4 on 2024-12-25 21:49

import django.db.models.deletion
import modules.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='channel.channel')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer')),
            ],
            options={
                'db_table': 'order',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='order.order')),
            ],
            options={
                'db_table': 'order_address',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
            options={
                'db_table': 'order_item',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='OrderItemAdditive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additives', to='order.orderitem')),
            ],
            options={
                'db_table': 'order_item_additive',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='OrderItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='order.orderitem')),
            ],
            options={
                'db_table': 'order_item_variant',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_item_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='order.orderitemvariant')),
            ],
            options={
                'db_table': 'order_package',
            },
            bases=(models.Model, modules.base.models.TimeStampeMixin),
        ),
    ]
